/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'surface-bright': '#fbf9f8',
        'on-secondary-fixed': '#400100',
        'secondary': '#b52617',
        'error': '#ba1a1a',
        'surface-container-low': '#f6f3f2',
        'on-surface-variant': '#454652',
        'primary-container': '#1a237e',
        'background': '#fbf9f8',
        'inverse-primary': '#bdc2ff',
        'on-surface': '#1b1c1c',
        'on-secondary': '#ffffff',
        'on-secondary-fixed-variant': '#920701',
        'on-tertiary-container': '#979898',
        'on-secondary-container': '#600200',
        'on-tertiary-fixed-variant': '#464747',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#000767',
        'tertiary-container': '#2f3030',
        'tertiary-fixed': '#e3e2e2',
        'secondary-fixed': '#ffdad4',
        'on-background': '#1b1c1c',
        'surface-variant': '#e4e2e1',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#bdc2ff',
        'tertiary': '#1a1b1c',
        'on-primary-container': '#8690ee',
        'error-container': '#ffdad6',
        'surface-container': '#f0eded',
        'primary': '#000666',
        'surface-tint': '#4c56af',
        'surface-container-high': '#eae8e7',
        'surface-dim': '#dcd9d9',
        'secondary-fixed-dim': '#ffb4a7',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e0e0ff',
        'outline-variant': '#c6c5d4',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#303030',
        'surface-container-highest': '#e4e2e1',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#f3f0f0',
        'tertiary-fixed-dim': '#c6c6c6',
        'outline': '#767683',
        'on-primary-fixed-variant': '#343d96',
        'secondary-container': '#ff5c45',
        'surface': '#fbf9f8',
        'on-tertiary-fixed': '#1a1c1c',
        'silver': '#c0c0c0',
        'sky-blue': '#87CEEB',
      },
      fontFamily: {
        'headline': ['Hanken Grotesk', 'sans-serif'],
        'body': ['Libre Franklin', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      spacing: {
        'section-gap-mobile': '48px',
        'gutter': '24px',
        'section-gap-desktop': '80px',
        'margin-desktop': '64px',
        'base': '8px',
        'margin-mobile': '20px',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
